#+TITLE: Programming in Haskell - Graham Hutton - Ch11 - Unbeatable Tic-Tac-Toe
#+AUTHOR: Firwanaa
#+PROPERTY: header-args :tangle code.hs
#+auto_tangle: t
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#imports][Imports]]
- [[#basic-declarations][Basic declarations]]
  - [[#grid][Grid]]
  - [[#player][Player]]
  - [[#next][Next]]
- [[#grid-utilities][Grid utilities]]
  - [[#empty][Empty]]
  - [[#empty-1][Empty]]
  - [[#turn][Turn]]
  - [[#win][Win]]
  - [[#diag][Diag]]
  - [[#won][Won]]
- [[#something][Something]]
- [[#displaying-a-grid][Displaying a grid]]
- [[#making-a-move][Making a move]]
  - [[#valid][valid]]
  - [[#move][move]]
- [[#reading-a-number][Reading a number]]
  - [[#getnat][getNat]]
- [[#human-vs-human][Human vs human]]
  - [[#run][run']]
- [[#game-tree][Game tree]]
- [[#pruning-the-tree][Pruning the tree]]
- [[#minmax-algorithm][Minmax algorithm]]
- [[#human-vs-computer][Human vs computer]]

* Imports
#+begin_src haskell
import Data.List
import Data.Char
import System.IO
#+end_src

* Basic declarations
** Grid
#+begin_src haskell
-- You can change the grid size here
size :: Int
size = 3

-- we represent the grid as list of lists of player values [[player]]
type Grid = [[Player]]
#+end_src
** Player
Player value is either O, B or X, where the extra B represents a blank space
#+begin_src haskell
data Player = O | B | X deriving (Eq, Ord, Show)

-- example of winning grid
-- [[B,O,O]]
-- [[O,X,O]]
-- [[X,X,X]]
#+end_src
** Next
The next player to move is given simply by swapping between O and X, with the case for the blank value B being included for completeness even though the function should never be applied to this value
#+begin_src haskell
next :: Player -> Player
next O = X
next B = B
next X = O
#+end_src

* Grid utilities
We make use of a number of utilities on tic-tac-toe grids.
** Empty
First of all, we define the empty grid by replicating the blank player value to create an empty row,and then replicating this row to create an empty grid.
#+begin_src haskell
empty :: Grid
empty = replicate size (replicate size B)

-- [[B,B,B]]
-- [[B,B,B]]
-- [[B,B,B]]
#+end_src
** Empty
Grid is full if all of its player values are non-blank
#+begin_src haskell
full :: Grid -> Bool
full = all (/=B) . concat
-- concat will flatten the list to single list, otherwise "all" will fail

-- all duplicate functions are me just practicing
full1 :: Grid -> Bool
full1 xs = all (/=B) $ concat xs

full2 :: Grid -> Bool
full2 xs = all (==B) [y | y <- concat xs]
#+end_src
** Turn
Decide whose turn it is by comparing the number of O’s and X’s in a flattened grid.
#+begin_src haskell
turn :: Grid -> Player
turn g = if os <= xs then O else X
         where
           os = length (filter (==O) ps)
           xs = length (filter (==X) ps)
           ps = concat g
#+end_src
** Win
If a player has a complete line in any row, column, or either diagonal in the grid
#+begin_src haskell
wins :: Player -> Grid -> Bool
wins p g = any line (rows ++ cols ++ dias)
           where
             line = all (==p)
             rows = g
             cols = transpose g -- transpose is a function from Data.List, converts grid cols into rows
             dias = [diag g, diag (map reverse g)]
#+end_src
** Diag
Returns diagonal of grid
#+begin_src haskell
diag :: Grid -> [Player]
diag g = [g !! n !! n | n <- [0..size-1]]
--eg.
-- > testList =
-- [[1,2,3]]
-- [[4,5,6]]
-- [[7,8,9]]
-- > diag testList = [testList !! n !! n | n <- [0..size-1]]
--                 = [testList !! 0 !! 0 | 0 <- [0..(2)]] = [1]    -- which is (0,0)
--                 = [testList !! 1 !! 1 | 1 <- [0..(2)]] = [1,5]  -- which is (1,1)
--                 = [testList !! 2 !! 2 | 2 <- [0..(2)]] = [1,5,9]-- which is (2,2)
-- > [1,5,9]
-- > diag (map reverse testList)
-- map reverse testList
-- [[3,2,1]]
-- [[6,5,4]]
-- [[9,8,7]]
-- diag (the new list above)
-- [3,5,7]
-- resutl of [diag testList, diag (map reverse testList)]
-- > [[1,5,9],[3,5,7]]
#+end_src
** Won
To decide if either player has won
* Something
#+begin_src haskell
won :: Grid -> Bool
won g = wins O g || wins X g
#+end_src

* Displaying a grid
we seek to define a function with the following example behaviour.

#+begin_src
> putGrid [[B,O,O],[O,X,O],[X,X,X]]
        |   |
        | O | O
        |   |
---------------------
        |   |
      O | X | O
        |   |
---------------------
        |   |
      X | X | X
        |   |

#+end_src
Can be achieved by using this function
#+begin_src haskell
putGrid :: Grid -> IO ()
putGrid = putStrLn . unlines . concat . interleave bar . map showRow
          where bar = [replicate ((size*4)-1) '-']

-- convert each row to a list of strings
showRow :: [Player] -> [String]
showRow = beside . interleave bar . map showPlayer
          where
            beside = foldr1 (zipWith (++))
            bar = replicate 3 "|"

-- convert a player value to a list of strings
showPlayer :: Player -> [String]
showPlayer O = ["   ", " O ", "  "]
showPlayer B = ["   ", "   ", "  "]
showPlayer X = ["   ", " X ", "  "]

-- interleave a value between each element in the list
interleave :: a -> [a] -> [a]
interleave x []     = []
interleave x [y]    = [y]
interleave x (y:ys) = y : x : interleave x ys
#+end_src

* Making a move
To identify where a player wishes to make a move during the game, we index each position in the grid by a natural number, starting from zero in the top-left corner and proceeding along each row in turn.
+-----+-----+-----+
|  0  |  1  |  2  |
+-----+-----+-----+
|  3  |  4  |  5  |
+-----+-----+-----+
|  6  |  7  |  8  |
+-----+-----+-----+
** valid
Attempting to make a move at a particular index is valid if the index is within the appropriate range, and the position is currently blank.
#+begin_src haskell
valid :: Grid -> Int -> Bool
valid g i = O <= i && < size^2 && concat g !! == B
#+end_src
** move
We now define a function that applies a move to a grid.
#+begin_src haskell
move :: Grid -> Int -> Player [Grid]
move g i p = if valid g i then [chop size (xs ++ [p] ys)] else []
             where (xs,B:ys) = splitAt i (concat g)

chop :: Int -> [a] -> [[a]]
chop n [] = []
chop n xs = take n xs : chop n (drop n xs)
#+end_src

* Reading a number
To read a grid index from a human player, we define a function getNat that displays a prompt and reads a natural number from the keyboard.
** getNat
#+begin_src haskell
getNat :: String -> IO Int
getNat prompt = do putStr prompt
                   xs <- getLine
                   if xs /= [] && all isDigit xs then -- isDigit provided in Data.Char
                      return (read xs)
                   else
                      do putStrLn "Error: Invalid number"
                         getNat prompt
#+end_src

* Human vs human
We define an action that implements the game using two mutually recursive functions that take the current grid and player as argument
#+begin_src haskell
tictactoe :: IO ()
tictactoe = run empty O

run :: Grid -> Player -> IO ()
run g p = do cls
             goto(1,1)
             putGrid g
             run' g p

type Pos = (Int, Int)

cls :: IO ()
cls = putStr "\ESC[2J"

goto :: Pos -> IO ()
goto (x,y) = putStr ("\ESC[" ++ show y ++ ";" ++ show x ++ "H")

prompt :: Player -> String
prompt p = "Player " ++ show p ++ ", enter your move: "
#+end_src
** run'
#+begin_src haskell
run’ :: Grid -> Player -> IO ()
run’ g p | wins O g = putStrLn "Player O wins!\n"
         | wins X g = putStrLn "Player X wins!\n"
         | full g = putStrLn "It’s a draw!\n"
         | otherwise =
              do i <- getNat (prompt p)
              case move g i p of
              [] -> do putStrLn "ERROR: Invalid move"
                       run’ g p
              [g’] -> run g’ (next p)
#+end_src

* Game tree
#+begin_src haskell
data Tree a = Node a [Tree a]
              deriving Show

gametree :: Grid -> Player -> Tree Grid
gametree g p = Node g [gametree g’ (next p) | g’ <- moves g p]

moves :: Grid -> Player -> [Grid]
moves g p
   | won g = []
   | full g = []
   | otherwise = concat [move g i p | i <- [0..((size^2)-1)]]
#+end_src

* Pruning the tree
#+begin_src haskell
prune :: Int -> Tree a -> Tree a
prune 0 (Node x _) = Node x []
prune n (Node x ts) = Node x [prune (n-1) t | t <- ts]

depth :: Int
depth = 9
#+end_src

* Minmax algorithm
#+begin_src haskell
minimax :: Tree Grid -> Tree (Grid,Player)
minimax (Node g [])
   | wins O g = Node (g,O) []
   | wins X g = Node (g,X) []
   | otherwise = Node (g,B) []
minimax (Node g ts)
   | turn g == O = Node (g, minimum ps) ts’
   | turn g == X = Node (g, maximum ps) ts’
                   where
                      ts’ = map minimax ts
                      ps = [p | Node (_,p) _ <- ts’]

bestmove :: Grid -> Player -> Grid
bestmove g p = head [g’ | Node (g’,p’) _ <- ts, p’ == best]
               where
                  tree = prune depth (gametree g p)
                  Node (_,best) ts = minimax tree
#+end_src
* Human vs computer
#+begin_src haskell
main :: IO ()
main = do hSetBuffering stdout NoBuffering
          play empty O

play :: Grid -> Player -> IO ()
play g p = do cls
              goto (1,1)
              putGrid g
              play’ g p

play’ :: Grid -> Player -> IO ()
play’ g p
   | wins O g = putStrLn "Player O wins!\n"
   | wins X g = putStrLn "Player X wins!\n"
   | full g = putStrLn "It’s a draw!\n"
   | p == O = do i <- getNat (prompt p)
                 case move g i p of
                   [] -> do putStrLn "ERROR: Invalid move"
                            play’ g p
                   [g’] -> play g’ (next p)
   | p == X = do putStr "Player X is thinking... "
                 (play $! (bestmove g p)) (next p)
#+end_src
